@LibraryAPI_HostAddress = http://localhost:5108

POST {{LibraryAPI_HostAddress}}/api/library/newuser
Content-Type: application/json
{
  "Name": "testname01",
  "UserType": "ExternalUser"
}
###
POST {{LibraryAPI_HostAddress}}/api/library/newitem
Content-Type: application/json
{
  "Name": "testitem01",
  "ItemType": "BoardGame"
}

###
GET {{LibraryAPI_HostAddress}}/api/library/24fda861-7192-4e08-bebb-612a2c8fc059
Accept: application/json

###
POST {{LibraryAPI_HostAddress}}/api/library/newborrowing
Content-Type: application/json
{
  "UserId": "24fd5861-7192-4e08-bebb-612a2c8fc059",
  "ItemId": "bf442c52-c01f-4171-b700-1af04220d317"
}