@LibraryAPI_HostAddress = http://localhost:5108

POST {{LibraryAPI_HostAddress}}/api/library/newuser
Content-Type: application/json
{
  "Name": "testname01",
  "UserType": "ExternalUser"
}
###
POST {{LibraryAPI_HostAddress}}/api/library/newitem
Content-Type: application/json
{
  "Name": "testitem01",
  "ItemType": "Book"
}

###
GET {{LibraryAPI_HostAddress}}/api/library/d01a4ee9-a960-4db6-8963-91629703a4b0
Accept: application/json

###
POST {{LibraryAPI_HostAddress}}/api/library/newborrowing
Content-Type: application/json
{
  "UserId": "d01a4ee9-a960-4db6-8963-91629703a4b0",
  "ItemId": "0f508097-ed59-4753-bd38-4a51dcbf7c23"
}